# Generated by Django 5.0 on 2023-12-29 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformas',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proformas',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
