# Generated by Django 5.0 on 2024-01-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0004_alter_proformas_numero_proforma'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proformas',
            new_name='Proforma',
        ),
    ]
