# Generated by Django 5.0 on 2024-02-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0005_rename_proformas_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
