# Generated by Django 5.0 on 2024-02-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0006_proforma_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
