# Generated by Django 5.0 on 2024-02-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0007_proforma_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='cliente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
